on: [push, pull_request]
name: Test
permissions: {}
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x,1.21.x,1.22.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: make test
